[project]
name = "my-prisma"
version = "0.1.0"
description = "Shared Prisma models package"
requires-python = ">=3.10"

dependencies = [
    "prisma>=0.11.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["my_prisma"]
